### ISSUE TITLE
Exception is thrown when client is disconnected from server.

### ISSUE THREAD

**Issue by Davidnovarro** [vis2k/Telepathy#82]
The exception is thrown every time the client disconnects from the server. 
NOTE: I'm the running on Linux platform with the NET Core version: "2.2.207".

`Exception thrown: 'System.PlatformNotSupportedException' in System.Threading.Thread.dll
Server client thread exception: System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at Telepathy.ThreadExtensions.AbortAndJoin(Thread thread) in C:\Projects\PartyServer\PartyServer\Messaging\Transport\Telepathy\ThreadExtensions.cs:line 14
   at Telepathy.Server.<>c__DisplayClass8_0.<Listen>b__1() in C:\Projects\PartyServer\PartyServer\Messaging\Transport\Telepathy\Server.cs:line 150`

**Comment by gkaragoz** [comment]
Same exception here on Windows 10 user withg .NET Core version 3.1.100

**Comment by vis2k** [comment]
works again in master. thx
